# Generated by Django 4.2.6 on 2023-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.AddField(
            model_name='books',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='books',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
