# Generated by Django 4.2.6 on 2023-12-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_price_books_about_books_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
